## Importing Data

In [2]:
import pandas as pd
import numpy as np
title= pd.read_csv('Title_Defect_Dataset.csv')
title.head()

Property_ID  StatusOwnerOccupiedFlag  TaxAssessedValueTotal  \
0    244558691                      NaN                18500.0   
1    168532803                      1.0               110000.0   
2    170243135                      1.0               190000.0   
3     50276190                      1.0               191000.0   
4     38057038                      1.0               110000.0   

   TaxAssessedImprovementsPerc  TaxMarketValueTotal  \
0                          0.0              18450.0   
1                         90.0             183333.0   
2                         81.0             316667.0   
3                         91.0             318333.0   
4                         75.0             183333.0   

   TaxMarketImprovementsPerc  AreaBuilding  BedroomsCount  StoriesCount  \
0                        NaN          1716              4           2.0   
1                        NaN          1192              3           1.0   
2                        NaN          3484              3           2.0   
3                        NaN          2400              4           1.0   
4                        NaN          1200              3           1.0   

   DeckFlag  ...  X_PERC_CDPD60  X_PERC_CForeclosure  X_PERC_CDerogatory  \
0       0.0  ...           11.0                 11.0                11.0   
1       0.0  ...           19.0                  0.0                16.0   
2       0.0  ...           19.0                  0.0                16.0   
3       0.0  ...           19.0                  0.0                16.0   
4       0.0  ...           19.0                  0.0                16.0   

   X_PERC_CBankruptcy  X_PERC_MDPD60  X_PERC_MDerogatory  X_PERC_MBankruptcy  \
0                 0.0           11.0                11.0                 0.0   
1                 0.0            3.0                 3.0                 0.0   
2                 0.0            3.0                 3.0                 0.0   
3                 0.0            3.0                 3.0                 0.0   
4                 0.0            3.0                 3.0                 0.0   

   X_Bankruptcy_Index  X_Risk_Score  X_Vantage_Score  
0               287.0         727.0            817.0  
1               295.0         744.0            825.0  
2               295.0         744.0            825.0  
3               295.0         744.0            825.0  
4               295.0         744.0            825.0  

[5 rows x 52 columns]

In [3]:
data = title[['TaxAssessedValueTotal',
       'TaxMarketValueTotal', 'dr_Title_Defect_Ind', 'dr_MktValueToIncome',
       'dr_Condo_Ind', 'dr_Ownership_Period', 'dr_House_Age',
       'dr_Value_Change', 'X_PERC_CDPD60', 'X_PERC_CForeclosure',
       'X_PERC_CDerogatory', 'X_PERC_CBankruptcy', 'X_PERC_MDPD60', 'X_PERC_MBankruptcy',
       'X_Bankruptcy_Index', 'X_Risk_Score', 'X_Vantage_Score']]
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500250 entries, 0 to 500249
Data columns (total 17 columns):
TaxAssessedValueTotal    500173 non-null float64
TaxMarketValueTotal      500173 non-null float64
dr_Title_Defect_Ind      500250 non-null int64
dr_MktValueToIncome      496926 non-null float64
dr_Condo_Ind             500250 non-null int64
dr_Ownership_Period      361899 non-null float64
dr_House_Age             447048 non-null float64
dr_Value_Change          500250 non-null object
X_PERC_CDPD60            454631 non-null float64
X_PERC_CForeclosure      454631 non-null float64
X_PERC_CDerogatory       454631 non-null float64
X_PERC_CBankruptcy       454631 non-null float64
X_PERC_MDPD60            454631 non-null float64
X_PERC_MBankruptcy       454631 non-null float64
X_Bankruptcy_Index       454631 non-null float64
X_Risk_Score             454631 non-null float64
X_Vantage_Score          454631 non-null float64
dtypes: float64(14), int64(2), object(1)
memory usage: 64.9+ 

## Data cleaning

In [4]:
#Replacing INC, DEC, NC with integers
data.replace(to_replace=['INC','DEC','NC'], value= [1,-1,0], inplace=True)

C:\Users\sherr\Anaconda3\lib\site-packages\pandas\core\frame.py:4042: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  method=method)


In [5]:
#Drop all rows with a missing value in all columns
# revised_data= data.dropna()
# revised_data

StatusOwnerOccupiedFlag  TaxAssessedValueTotal  TaxMarketValueTotal  \
2                           1.0               190000.0             316667.0   
3                           1.0               191000.0             318333.0   
4                           1.0               110000.0             183333.0   
7                           1.0               142400.0             167529.0   
9                           1.0               124400.0             146353.0   
...                         ...                    ...                  ...   
500236                      1.0               130000.0             130000.0   
500238                      1.0               150000.0             150000.0   
500240                      1.0               215000.0             215000.0   
500243                      1.0               190000.0             190000.0   
500247                      1.0               210000.0             210000.0   

        dr_Title_Defect_Ind  dr_MktValueToIncome  dr_Condo_Ind  \
2                         0                 3.98             0   
3                         0                 4.00             0   
4                         0                 2.30             0   
7                         0                 2.10             0   
9                         0                 1.84             0   
...                     ...                  ...           ...   
500236                    0                 2.15             0   
500238                    0                 2.48             0   
500240                    0                 3.56             0   
500243                    0                 3.15             0   
500247                    0                 3.48             0   

        dr_Ownership_Period  dr_House_Age  dr_Value_Change  X_PERC_CDPD60  \
2                      19.0          18.0                0           19.0   
3                       0.0          39.0               -1           19.0   
4                      14.0          12.0                0           19.0   
7                      11.0          62.0                0           28.0   
9                       6.0          84.0                0           28.0   
...                     ...           ...              ...            ...   
500236                 18.0          68.0                0           10.0   
500238                 12.0          10.0                0           22.0   
500240                  6.0          98.0                0           16.0   
500243                  7.0          53.0                0            3.0   
500247                 17.0          42.0                0           12.0   

        X_PERC_CForeclosure  X_PERC_CDerogatory  X_PERC_CBankruptcy  \
2                       0.0                16.0                 0.0   
3                       0.0                16.0                 0.0   
4                       0.0                16.0                 0.0   
7                       0.0                28.0                 0.0   
9                       0.0                28.0                 0.0   
...                     ...                 ...                 ...   
500236                  0.0                 5.0                 0.0   
500238                  0.0                16.0                 0.0   
500240                  0.0                11.0                 0.0   
500243                  0.0                 3.0                 0.0   
500247                  0.0                12.0                 0.0   

        X_PERC_MDPD60  X_PERC_MDerogatory  X_PERC_MBankruptcy  \
2                 3.0                 3.0                 0.0   
3                 3.0                 3.0                 0.0   
4                 3.0                 3.0                 0.0   
7                 7.0                 7.0                 0.0   
9                 7.0                 7.0                 0.0   
...               ...                 ...                 ...   
500236            0.0            

#### Impute missing value

In [5]:
import pandas as pd
import sklearn.preprocessing

trainingData = data.iloc[:, :].values
data_1 = data.iloc[:, :].values


from sklearn.impute import SimpleImputer 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

# return the col# that has NaN values:
index=[]
for m in range(len(list(data))):
    if data.iloc[:, m].isna().sum() != 0:
        index.append(m)

#impute
for i in range(17):
    imputer = imputer.fit(trainingData[:, i:(i+1)])
    data_1[:, i:(i+1)] = imputer.transform(data_1[:, i:(i+1)])

# data_1.drop(columns=['dr_Title_Defect_Ind'])

# data_2 = pd.DataFrame(data_1).rename(columns={1: 'TaxAssessedValueTotal'})
# data_2
# simple_imputer = SimpleImputer(add_indicator=True)
# simple_imputer.fit(X)
# print(simple_imputer.indicator_.features_)

In [6]:
# index=[]
# for i in range(len(list(data))):
#     if data.iloc[:, i].isna().sum() != 0:
#         index.append(i)

for m in range(17):   
    data_1 = pd.DataFrame(data_1).rename(columns={m: list(data)[m]})

revised_data = pd.DataFrame(data_1)
revised_data.info()
# list(data)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500250 entries, 0 to 500249
Data columns (total 17 columns):
TaxAssessedValueTotal    500250 non-null float64
TaxMarketValueTotal      500250 non-null float64
dr_Title_Defect_Ind      500250 non-null float64
dr_MktValueToIncome      500250 non-null float64
dr_Condo_Ind             500250 non-null float64
dr_Ownership_Period      500250 non-null float64
dr_House_Age             500250 non-null float64
dr_Value_Change          500250 non-null float64
X_PERC_CDPD60            500250 non-null float64
X_PERC_CForeclosure      500250 non-null float64
X_PERC_CDerogatory       500250 non-null float64
X_PERC_CBankruptcy       500250 non-null float64
X_PERC_MDPD60            500250 non-null float64
X_PERC_MBankruptcy       500250 non-null float64
X_Bankruptcy_Index       500250 non-null float64
X_Risk_Score             500250 non-null float64
X_Vantage_Score          500250 non-null float64
dtypes: float64(17)
memory usage: 64.9 MB


### Train Test Split

In [7]:
#Create x and y for training
y = revised_data['dr_Title_Defect_Ind']
X = revised_data[['TaxAssessedValueTotal', 'TaxMarketValueTotal', 'dr_MktValueToIncome',
       'dr_Condo_Ind', 'dr_Ownership_Period', 'dr_House_Age',
       'dr_Value_Change', 'X_PERC_CDPD60', 'X_PERC_CForeclosure',
       'X_PERC_CDerogatory', 'X_PERC_CBankruptcy', 'X_PERC_MDPD60', 'X_PERC_MBankruptcy', 'X_Bankruptcy_Index',
       'X_Risk_Score', 'X_Vantage_Score']]

X.head()

TaxAssessedValueTotal  TaxMarketValueTotal  dr_MktValueToIncome  \
0                18500.0              18450.0                 0.22   
1               110000.0             183333.0                 2.30   
2               190000.0             316667.0                 3.98   
3               191000.0             318333.0                 4.00   
4               110000.0             183333.0                 2.30   

   dr_Condo_Ind  dr_Ownership_Period  dr_House_Age  dr_Value_Change  \
0           0.0              0.00000         118.0              1.0   
1           0.0             10.41382          33.0              0.0   
2           0.0             19.00000          18.0              0.0   
3           0.0              0.00000          39.0             -1.0   
4           0.0             14.00000          12.0              0.0   

   X_PERC_CDPD60  X_PERC_CForeclosure  X_PERC_CDerogatory  X_PERC_CBankruptcy  \
0           11.0                 11.0                11.0                 0.0   
1           19.0                  0.0                16.0                 0.0   
2           19.0                  0.0                16.0                 0.0   
3           19.0                  0.0                16.0                 0.0   
4           19.0                  0.0                16.0                 0.0   

   X_PERC_MDPD60  X_PERC_MBankruptcy  X_Bankruptcy_Index  X_Risk_Score  \
0           11.0                 0.0               287.0         727.0   
1            3.0                 0.0               295.0         744.0   
2            3.0                 0.0               295.0         744.0   
3            3.0                 0.0               295.0         744.0   
4            3.0                 0.0               295.0         744.0   

   X_Vantage_Score  
0            817.0  
1            825.0  
2            825.0  
3            825.0  
4            825.0

In [14]:
#Train test split and gridserach to tune model
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [15]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

### SMOTE balance train set

In [10]:
# pip install imblearn (if you don't have imblearn in your system) 
# from imblearn.over_sampling import SMOTE 
# sm = SMOTE(random_state = 2) 
# X_train_res, y_train_res = sm.fit_sample(X_train, y_train.ravel()) 

In [107]:
from imblearn.combine import SMOTETomek
from sklearn.metrics import classification_report

smt = SMOTETomek()
X_smt, y_smt = smt.fit_sample(X, y)
X_train_smt, X_test_smt, y_train_smt, y_test_smt = train_test_split(X_smt, y_smt, random_state=42)

In [108]:
# X_train_smt.info()
# X_test_smt.info()
# y_train_smt
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train_smt)



# X_train.info()
# X_test.info()
# y_train

StandardScaler()

In [109]:
X_train_smt.info()
X_test_smt.info()
y_train_smt

<class 'pandas.core.frame.DataFrame'>
Int64Index: 742966 entries, 705080 to 121958
Data columns (total 16 columns):
TaxAssessedValueTotal    742966 non-null float64
TaxMarketValueTotal      742966 non-null float64
dr_MktValueToIncome      742966 non-null float64
dr_Condo_Ind             742966 non-null float64
dr_Ownership_Period      742966 non-null float64
dr_House_Age             742966 non-null float64
dr_Value_Change          742966 non-null float64
X_PERC_CDPD60            742966 non-null float64
X_PERC_CForeclosure      742966 non-null float64
X_PERC_CDerogatory       742966 non-null float64
X_PERC_CBankruptcy       742966 non-null float64
X_PERC_MDPD60            742966 non-null float64
X_PERC_MBankruptcy       742966 non-null float64
X_Bankruptcy_Index       742966 non-null float64
X_Risk_Score             742966 non-null float64
X_Vantage_Score          742966 non-null float64
dtypes: float64(16)
memory usage: 96.4 MB
<class 'pandas.core.frame.DataFrame'>
Int64Index: 247656 e

705080    1.0
119624    0.0
304025    0.0
370171    0.0
330690    0.0
         ... 
259178    0.0
365838    0.0
131932    0.0
671155    1.0
121958    0.0
Name: dr_Title_Defect_Ind, Length: 742966, dtype: float64

## Logistic Regression

In [110]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
import seaborn as sn
import matplotlib.pyplot as plt

In [111]:
# model
logistic_regression= LogisticRegression()
logistic_regression.fit(X_train_smt,y_train_smt)
lg_pred_i=logistic_regression.predict(X_test_smt)

In [62]:
# # model
# logistic_regression= LogisticRegression(class_weight = 'balanced')
# logistic_regression.fit(X_train,y_train)
# lg_pred=logistic_regression.predict(X_test)

In [116]:
lg_pred_i

array([1., 1., 0., ..., 0., 1., 0.])

In [113]:
# Evaluation later

print ("Logistic Confusion Matrix : \n", confusion_matrix(y_test_smt, lg_pred_i),"\n") 
print ("Logistic Accuracy : ", accuracy_score(y_test_smt, lg_pred_i),"\n") 
print ("Logistic RMSE : ", sqrt(mean_squared_error(y_test_smt, lg_pred_i)),"\n")
print ("Logistic Classification : \n", classification_report(y_test_smt, lg_pred_i))
print ("Logistic ROC_AUC : ",roc_auc_score(y_test_smt, lg_pred_i))

Logistic Confusion Matrix : 
 [[89744 33968]
 [48857 75087]] 

Logistic Accuracy :  0.6655643311690409 

Logistic RMSE :  0.5783041317775268 

Logistic Classification : 
               precision    recall  f1-score   support

         0.0       0.65      0.73      0.68    123712
         1.0       0.69      0.61      0.64    123944

    accuracy                           0.67    247656
   macro avg       0.67      0.67      0.66    247656
weighted avg       0.67      0.67      0.66    247656

Logistic ROC_AUC :  0.6656203568428964


In [112]:
logistic_regression.predict_proba(X_test_smt)[:,1].tolist()

[0.5811542236890999,
 0.7854032096284415,
 0.33927679608224154,
 0.5194305388454945,
 0.6637845620863262,
 0.910494058796141,
 0.4610718934053021,
 0.7696255604043785,
 0.21613345932137856,
 0.3995753606459409,
 0.2751857347482228,
 0.2652298991015399,
 0.7434805543907214,
 0.27241688792917695,
 0.5486073722901594,
 0.6673470076658419,
 0.5281222400870021,
 0.7804555364192467,
 0.3028546058636111,
 0.8401468969014984,
 0.5184738175482279,
 0.5175320827057266,
 0.7960877392965188,
 0.5579203176848403,
 0.5976126035819788,
 0.2694665804961823,
 0.7310906698982566,
 0.30611025179755774,
 0.9259111738972295,
 0.22052334313433822,
 0.8012194988577864,
 0.7468973822975264,
 0.5701648613919177,
 0.5257712704449844,
 0.4220792910823357,
 0.6085252379264111,
 0.4068444195713205,
 0.5516970357805769,
 0.604419190387309,
 0.3718285569771849,
 0.3193545309813534,
 0.5011667929223881,
 0.542225786497993,
 0.7103685143761812,
 0.6976810682606522,
 0.4168480496807248,
 0.3965412126069324,
 0.26011743

In [63]:
# evaluation before
# print ("Logistic Confusion Matrix : \n", confusion_matrix(y_test, lg_pred),"\n") 
# print ("Logistic Accuracy : ", accuracy_score(y_test, lg_pred),"\n") 
# print ("Logistic RMSE : ", sqrt(mean_squared_error(y_test, lg_pred)),"\n")
# print ("Logistic Classification : \n", classification_report(y_test, lg_pred))
# print ("Logistic ROC_AUC : ",roc_auc_score(y_test, lg_pred))

Logistic Confusion Matrix : 
 [[59247    54]
 [  117     0]] 

Logistic Accuracy :  0.997122084216904 

Logistic RMSE :  0.053646209401000844 

Logistic Classification : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     59301
           1       0.00      0.00      0.00       117

    accuracy                           1.00     59418
   macro avg       0.50      0.50      0.50     59418
weighted avg       1.00      1.00      1.00     59418

Logistic ROC_AUC :  0.4995446957049628


## Decision Tree

In [119]:
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier()
dtree = dtree.fit(X_train_smt,y_train_smt)
dtree_pred_i = dtree.predict(X_test_smt)

In [58]:
# from sklearn.tree import DecisionTreeClassifier
# dtree = DecisionTreeClassifier()
# dtree = dtree.fit(X_train,y_train)
# dtree_pred = dtree.predict(X_test)

In [115]:
# Evaluation (before)
from sklearn.metrics import confusion_matrix
from math import sqrt
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
from sklearn.metrics import roc_auc_score
from sklearn.metrics import mean_squared_error

print ("Decision Tree Confusion Matrix : \n", confusion_matrix(y_test_smt, dtree_pred_i),"\n" )
print ("Decision Tree Accuracy : ", accuracy_score(y_test_smt, dtree_pred_i),"\n")
print ("Decision Tree RMSE : ", sqrt(mean_squared_error(y_test_smt, dtree_pred_i)),"\n")
print ("Decision Tree Classification: \n", classification_report(y_test_smt, dtree_pred_i))
print ("Decision Tree ROC_AUC: ",roc_auc_score(y_test_smt, dtree_pred_i))

Decision Tree Confusion Matrix : 
 [[122713    999]
 [   660 123284]] 

Decision Tree Accuracy :  0.9933011919759667 

Decision Tree RMSE :  0.0818462462427773 

Decision Tree Classification: 
               precision    recall  f1-score   support

         0.0       0.99      0.99      0.99    123712
         1.0       0.99      0.99      0.99    123944

    accuracy                           0.99    247656
   macro avg       0.99      0.99      0.99    247656
weighted avg       0.99      0.99      0.99    247656

Decision Tree ROC_AUC:  0.9932999037952289


In [117]:
dtree.predict_proba(X_test_smt)[:,1].tolist()

[1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 1.0,
 0.0,
 0.0,
 1.0,
 1.0,
 1.0,
 0.0,
 0.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 1.0,
 1.0,
 0.0,
 0.0,
 0.0

In [59]:
# Evaluation
# print ("Decision Tree Confusion Matrix : \n", confusion_matrix(y_test, dtree_pred),"\n" )
# print ("Decision Tree Accuracy : ", accuracy_score(y_test, dtree_pred),"\n")
# print ("Decision Tree RMSE : ", sqrt(mean_squared_error(y_test, dtree_pred)),"\n")
# print ("Decision Tree Classification: \n", classification_report(y_test, dtree_pred))
# print ("Decision Tree ROC_AUC: ",roc_auc_score(y_test, dtree_pred))

Decision Tree Confusion Matrix : 
 [[59113   188]
 [  116     1]] 

Decision Tree Accuracy :  0.994883705274496 

Decision Tree RMSE :  0.07152827920133446 

Decision Tree Classification: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     59301
           1       0.01      0.01      0.01       117

    accuracy                           0.99     59418
   macro avg       0.50      0.50      0.50     59418
weighted avg       1.00      0.99      1.00     59418

Decision Tree ROC_AUC:  0.5026883708018933


### Tree Visualization

In [116]:
! pip install pydot
! pip install graphviz

In [114]:
from IPython.display import Image  
from sklearn.externals.six import StringIO  
from sklearn.tree import export_graphviz
import pydot 

features = ['TaxAssessedValueTotal', 'TaxMarketValueTotal', 'dr_MktValueToIncome',
       'dr_Condo_Ind', 'dr_Ownership_Period', 'dr_House_Age',
       'dr_Value_Change', 'X_PERC_CDPD60', 'X_PERC_CForeclosure',
       'X_PERC_CDerogatory', 'X_PERC_CBankruptcy', 'X_PERC_MDPD60',
       'X_PERC_MDerogatory', 'X_PERC_MBankruptcy', 'X_Bankruptcy_Index',
       'X_Risk_Score', 'X_Vantage_Score']

In [117]:
dot_data = StringIO()  
export_graphviz(dtree, out_file=dot_data, feature_names=features, filled=True, rounded=True)

graph = pydot.graph_from_dot_data(dot_data.getvalue())  
Image(graph[0].create_png())  

FileNotFoundError: [Errno 2] "dot" not found in path.

## Random Forest

In [120]:
from sklearn.ensemble import RandomForestClassifier

rfc = RandomForestClassifier(n_estimators=200)
rfc.fit(X_train_smt,y_train_smt)
rfc_pred = rfc.predict(X_test_smt)

In [121]:
# Evaluation later
print ("Random Forest Confusion Matrix : \n", confusion_matrix(y_test_smt, rfc_pred),"\n" )
print ("Random Forest Accuracy : ", accuracy_score(y_test_smt, rfc_pred),"\n")
print ("Random Forest RMSE : ", sqrt(mean_squared_error(y_test_smt, rfc_pred)),"\n")
print ("Random Forest Classification: \n", classification_report(y_test_smt, rfc_pred))
print ("Random Forest ROC_AUC: ",roc_auc_score(y_test_smt, rfc_pred))

Random Forest Confusion Matrix : 
 [[123540    172]
 [   419 123525]] 

Random Forest Accuracy :  0.9976136253512937 

Random Forest RMSE :  0.048850533760710024 

Random Forest Classification: 
               precision    recall  f1-score   support

         0.0       1.00      1.00      1.00    123712
         1.0       1.00      1.00      1.00    123944

    accuracy                           1.00    247656
   macro avg       1.00      1.00      1.00    247656
weighted avg       1.00      1.00      1.00    247656

Random Forest ROC_AUC:  0.9976145575598133


In [134]:
set(rfc.predict_proba(X_test_smt)[:,1].tolist())

{0.0,
 4.5045045045045046e-05,
 4.807692307692308e-05,
 6.17283950617284e-05,
 0.0001530612244897959,
 0.00015514592933947775,
 0.0002040816326530612,
 0.00020682466535001096,
 0.00026855306041173935,
 0.00045454545454545455,
 0.000625,
 0.0008333333333333333,
 0.001,
 0.00125,
 0.0014285714285714286,
 0.0016666666666666666,
 0.001875,
 0.002,
 0.0020833333333333333,
 0.0023333333333333335,
 0.0024285714285714284,
 0.0025,
 0.0027716810044175776,
 0.002833333333333333,
 0.002857142857142857,
 0.0028869047619047615,
 0.003,
 0.003333333333333333,
 0.00375,
 0.0038181818181818182,
 0.003918867151603725,
 0.004,
 0.004166666666666667,
 0.004446608946608947,
 0.0045000000000000005,
 0.004666666666666667,
 0.004702380952380953,
 0.005,
 0.005001087582740927,
 0.005056179775280899,
 0.005063947689145516,
 0.005818181818181818,
 0.005833333333333334,
 0.006,
 0.00625,
 0.006428571428571428,
 0.006500000000000001,
 0.006666666666666666,
 0.006742185510567864,
 0.006999999999999999,
 0.00717857

In [56]:
# rfc = RandomForestClassifier(n_estimators=200)
# rfc.fit(X_train,y_train)
# rfc_pred = rfc.predict(X_test)

In [57]:
# Evaluation before
# print ("Random Forest Confusion Matrix : \n", confusion_matrix(y_test, rfc_pred),"\n" )
# print ("Random Forest Accuracy : ", accuracy_score(y_test, rfc_pred),"\n")
# print ("Random Forest RMSE : ", sqrt(mean_squared_error(y_test, rfc_pred)),"\n")
# print ("Random Forest Classification: \n", classification_report(y_test, rfc_pred))
# print ("Random Forest ROC_AUC: ",roc_auc_score(y_test, rfc_pred))

Random Forest Confusion Matrix : 
 [[59292     9]
 [  117     0]] 

Random Forest Accuracy :  0.9978794304756134 

Random Forest RMSE :  0.04604964195720255 

Random Forest Classification: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00     59301
           1       0.00      0.00      0.00       117

    accuracy                           1.00     59418
   macro avg       0.50      0.50      0.50     59418
weighted avg       1.00      1.00      1.00     59418

Random Forest ROC_AUC:  0.49992411595082714


## KNN

In [23]:
# KNN

# from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import cross_val_score
# from sklearn.model_selection import RepeatedKFold
# from sklearn.neighbors import KNeighborsClassifier

# param_grid = {'n_neighbors': np.arange(1, 15, 2)} 

# grid = GridSearchCV(KNeighborsClassifier(), param_grid=param_grid, cv=10)

# grid.fit(X_train_res,y_train_res.ravel())

GridSearchCV(cv=10, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': array([ 1,  3,  5,  7,  9, 11, 13])})

In [24]:
# print("best parameters: {}".format(grid.best_params_))

best parameters: {'n_neighbors': 1}


In [131]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=3)
knn.fit(X_train_smt,y_train_smt)
knn_pred = knn.predict(X_test_smt)

In [133]:
set(knn.predict_proba(X_train_smt)[:,1].tolist())

{0.0, 0.3333333333333333, 0.6666666666666666, 1.0}

In [125]:
print ("KNN Confusion Matrix : \n", confusion_matrix(y_test_smt, knn_pred),"\n" )
print ("KNN Accuracy : ", accuracy_score(y_test_smt, knn_pred),"\n")
print ("KNN RMSE : ", sqrt(mean_squared_error(y_test_smt, knn_pred)),"\n")
print ("KNN Classification: \n", classification_report(y_test_smt, knn_pred))
print ("KNN ROC_AUC: ",roc_auc_score(y_test_smt, knn_pred))

KNN Confusion Matrix : 
 [[112755  10957]
 [  4755 119189]] 

KNN Accuracy :  0.9365571599315179 

KNN RMSE :  0.2518786216979958 

KNN Classification: 
               precision    recall  f1-score   support

         0.0       0.96      0.91      0.93    123712
         1.0       0.92      0.96      0.94    123944

    accuracy                           0.94    247656
   macro avg       0.94      0.94      0.94    247656
weighted avg       0.94      0.94      0.94    247656

KNN ROC_AUC:  0.9365336445582504


## XGBoost

In [18]:
import os
os.system("pip install xgboost")
import xgboost as xgb
import re
from xgboost.sklearn import XGBRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import cross_val_score
from numpy import loadtxt
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from math import sqrt
from sklearn.metrics import mean_squared_error

In [16]:
#Make predictions for test data
y_pred = model.predict(X_test)
predictions = [round(value) for value in y_pred]

model = XGBClassifier(n_estimators = 100,scale_pos_weight= 500)
model.fit(X_train, y_train)
y_pred = model.predict(X_test)

In [19]:
print ("Boost Confusion Matrix : \n", confusion_matrix(y_test, y_pred),"\n" )
print ("Boost Accuracy : ", accuracy_score(y_test, y_pred),"\n")
print ("Boost RMSE : ", sqrt(mean_squared_error(y_test, y_pred)),"\n")
print ("Boost Classification: \n", classification_report(y_test, y_pred))
print ("Boost ROC_AUC: ",roc_auc_score(y_test, y_pred))

Boost Confusion Matrix : 
 [[110726  13894]
 [   250    193]] 

Boost Accuracy :  0.8869049998800604 

Boost RMSE :  0.33629600074925 

Boost Classification: 
               precision    recall  f1-score   support

         0.0       1.00      0.89      0.94    124620
         1.0       0.01      0.44      0.03       443

    accuracy                           0.89    125063
   macro avg       0.51      0.66      0.48    125063
weighted avg       0.99      0.89      0.94    125063

Boost ROC_AUC:  0.6620874908933089
